# 指定action 名称
name: build docker image
# 指定触发时机
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
# 指定环境变量
env:
  IMAGE_NAME: test
  REGISTRY: outman2444
# 指定jobs
jobs:
  # 输出切分后的hash
  output_spiled_git_commit_hash:
    runs-on: ubuntu-latest
    outputs:
      hash: ${{ steps.spil_git_commit_hash.outputs.hash }}
    steps:
      - id: spil_git_commit_hash
        run: commit_hash=${{ github.event.commits[0].id }} && echo "::set-output name=hash::${commit_hash:0:7}"
  # 构建docker 镜像
  build_docker_image:
    # 在 ubuntu 环境中执行
    runs-on: ubuntu-latest
    needs: output_spiled_git_commit_hash
    env:
      COMMIT_HASH: ${{ needs.output_spiled_git_commit_hash.outputs.hash }}
    steps:
      #  检出代码
      - name: checkout code
        uses: actions/checkout@v3
      # 设置java 环境
      - name: set up jdk 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      #  编译打包
      - name: mvn build package
        run: mvn -B package --file pom.xml
      # 登录docker hub
      - name: login to docker hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: echo docker images
        run: docker images
      # 为docker 提取元数据
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
#      # 切分git commit hash
#      - name: spilt git hash
#        id: commit_hash
#        run: commit_hash=${{ github.event.commits[0].id }} && echo "${commit_hash:0:7}"
      # 构建docker 镜像
      - name: build docker image
#        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.commits[0].id }} .
#        run:  docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{steps.commit_hash.outputs}} .
        run:  docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{env.COMMIT_HASH}} .
      # 查看镜像
      - name: echo docker images
        run: docker images
      # push 镜像
      - name: docker push
#        run: docker push  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.commits[0].id }}
        run: docker push  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{env.COMMIT_HASH}}

#      # 构建 docker镜像  并发布到docker hub
#      - name: Build and push Docker image
#        id: build-and-push
#        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
#        with:
#          github-token: ${{ secrets.DOCKER_HUB_PASSWORD }}
#          context: .
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}